---
webapp_url:   soak:4567
tracker_type: yaml
tracker_name: /tmp/funder_tracker.yml
repo_url:     github.com/bugmark-trial/funder1
start_date:   2018-05-21
finish_date:  2018-05-24
scram_c3_volume: 20
scram_c2_volume: 20
scram_c1_volume: 20
scram_c0_volume: 20
scram_p3_volume: 20
scram_p2_volume: 20
scram_p1_volume: 20
scram_p0_volume: 20
